# Generated by Django 5.1.4 on 2025-01-02 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_nome', models.CharField(max_length=255, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('com_status', models.BooleanField(default=False, verbose_name='Status da Comanda')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'db_table': 'comanda',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('fpa_id', models.AutoField(primary_key=True, serialize=False)),
                ('fpa_tipo', models.CharField(max_length=60, unique=True, verbose_name='Tipo de Pagamento')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'db_table': 'forma_pagamento',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_nome', models.CharField(max_length=28, verbose_name='Nome do Cliente')),
                ('cli_sobrenome', models.CharField(max_length=28, null=True, verbose_name='Sobrenome do Cliente')),
                ('cli_aniversario', models.DateField(blank=True, null=True, verbose_name='Data de Aniversário')),
                ('cli_isActive', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cli_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('cli_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('cli_cidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('cli_bairro', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('cli_rua', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua')),
                ('cli_complemento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'unique_together': {('cli_email', 'cli_telefone')},
            },
        ),
        migrations.CreateModel(
            name='ClienteComanda',
            fields=[
                ('ccl_id', models.AutoField(primary_key=True, serialize=False)),
                ('ccl_data_abertura', models.DateField(verbose_name='Data da Associação')),
                ('ccl_data_fechamento', models.DateField(blank=True, null=True, verbose_name='Data do Desligamento')),
                ('cli_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandas', to='restaurante.cliente', verbose_name='Cliente')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='restaurante.comanda', verbose_name='Comanda')),
            ],
            options={
                'verbose_name': 'Cliente-Comanda',
                'verbose_name_plural': 'Clientes-Comandas',
                'db_table': 'cliente_comanda',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('fun_id', models.AutoField(primary_key=True, serialize=False)),
                ('fun_nome', models.CharField(max_length=255, verbose_name='Nome do Funcionário')),
                ('fun_aniversario', models.DateField(blank=True, null=True, verbose_name='Data de Aniversário')),
                ('fun_senha', models.CharField(blank=True, max_length=255, null=True, verbose_name='Senha')),
                ('fun_telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('fun_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
                ('fun_cpf', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'funcionario',
                'unique_together': {('fun_nome', 'fun_telefone')},
            },
        ),
        migrations.CreateModel(
            name='FuncionarioCliente',
            fields=[
                ('fcl_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='restaurante.cliente', verbose_name='Cliente')),
                ('fun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='restaurante.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Funcionário-Cliente',
                'verbose_name_plural': 'Funcionários-Clientes',
                'db_table': 'funcionario_cliente',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Menu')),
                ('menu_valor', models.FloatField(verbose_name='Valor do Menu')),
                ('menu_status', models.BooleanField(default=True, verbose_name='Status do Menu')),
                ('menu_descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Menu')),
                ('menu_imagem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Imagem do Menu')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurante.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'menu',
                'unique_together': {('menu_nome', 'menu_imagem')},
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('ped_id', models.AutoField(primary_key=True, serialize=False)),
                ('ped_data', models.DateField(blank=True, null=True, verbose_name='Data do Pedido')),
                ('ped_status', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='Status do Pedido')),
                ('ped_valorTotal', models.FloatField(blank=True, null=True, verbose_name='Valor Total')),
                ('cli_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='restaurante.cliente', verbose_name='Cliente')),
                ('fpa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='restaurante.formapagamento', verbose_name='Forma de Pagamento')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('ime_id', models.AutoField(primary_key=True, serialize=False)),
                ('ime_valorUnitario', models.FloatField(verbose_name='Valor Unitário')),
                ('ime_qtde', models.IntegerField(verbose_name='Quantidade')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='restaurante.menu', verbose_name='Menu')),
                ('ped_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='restaurante.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Menu',
                'verbose_name_plural': 'Itens do Menu',
                'db_table': 'item_menu',
            },
        ),
    ]
