# Generated by Django 5.1.4 on 2025-03-25 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_nome', models.CharField(max_length=18, verbose_name='Nome do Empregado')),
                ('emp_sobrenome', models.CharField(max_length=60, verbose_name='Sobrenome do Empregado')),
                ('emp_horarioTrabalho', models.CharField(max_length=13, verbose_name='Horario de Trabalho')),
                ('emp_rua', models.CharField(blank=True, max_length=60, null=True, verbose_name='Endereço da Rua')),
                ('emp_bairro', models.CharField(blank=True, max_length=28, null=True, verbose_name='Bairro')),
                ('emp_cidade', models.CharField(blank=True, max_length=28, null=True, verbose_name='Cidade')),
                ('emp_estado', models.CharField(max_length=28, null=True, verbose_name='Estado')),
                ('emp_salario', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Salario')),
                ('emp_dataAniversario', models.DateField(verbose_name='Data do Aniversário')),
            ],
            options={
                'verbose_name': 'Empregado',
                'verbose_name_plural': 'Empregados',
                'db_table': 'empregado',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_nome', models.CharField(max_length=28, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('com_id', models.IntegerField(primary_key=True, serialize=False)),
                ('com_status', models.BooleanField(default=False, verbose_name='Status da Comanda')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'db_table': 'comanda',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('fpa_id', models.AutoField(primary_key=True, serialize=False)),
                ('fpa_forma', models.CharField(max_length=42, verbose_name='Forma de Pagamento')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'db_table': 'formapagamento',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('mesa_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mesa_status', models.BooleanField(default=False, verbose_name='Status da Comanda')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'db_table': 'mesa',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_nome', models.CharField(max_length=28, verbose_name='Nome')),
                ('pro_gramagem', models.FloatField(verbose_name='Gramas')),
                ('pro_litragem', models.FloatField(verbose_name='Litros')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usu_id', models.AutoField(primary_key=True, serialize=False)),
                ('usu_telefone', models.CharField(max_length=16, verbose_name='Telefone')),
                ('usu_email', models.EmailField(max_length=120, verbose_name='Email')),
                ('usu_password', models.CharField(max_length=120, verbose_name='Senha')),
                ('usu_username', models.CharField(max_length=18, unique=True, verbose_name='Nome de Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('empregado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurante.empregado')),
            ],
            options={
                'managed': False,
            },
            bases=('restaurante.empregado',),
        ),
        migrations.CreateModel(
            name='Garcom',
            fields=[
                ('empregado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='restaurante.empregado')),
            ],
            options={
                'managed': False,
            },
            bases=('restaurante.empregado',),
        ),
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('car_valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor')),
                ('car_status', models.BooleanField(default=True, verbose_name='Status')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Cardapio',
                'db_table': 'cardapio',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_nome', models.CharField(max_length=28, verbose_name='Nome do Cliente')),
                ('cli_sobrenome', models.CharField(max_length=60, verbose_name='Sobrenome do Cliente')),
                ('cli_telefone', models.CharField(max_length=16, verbose_name='Telefone do Cliente')),
                ('cli_email', models.EmailField(max_length=120, unique=True, verbose_name='Email')),
                ('cli_dataNascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cli_rua', models.CharField(max_length=60, verbose_name='Rua do Cliente')),
                ('cli_numeroCasa', models.CharField(max_length=6, verbose_name='Numero da Casa')),
                ('cli_bairro', models.CharField(max_length=28, verbose_name='Bairro do Cliente')),
                ('cli_cidade', models.CharField(max_length=28, verbose_name='Cidade do Cliente')),
                ('cli_estado', models.CharField(max_length=28, verbose_name='Estado do Cliente')),
                ('cli_complemento', models.CharField(max_length=120, verbose_name='Complemento do Endereço')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'unique_together': {('cli_email', 'cli_telefone')},
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('ped_id', models.AutoField(primary_key=True, serialize=False)),
                ('ped_dataAbertura', models.DateField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('ped_dataFechamento', models.DateField(verbose_name='Data de Fechamento')),
                ('ped_status', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='Status do Pedido')),
                ('ped_valorTotal', models.FloatField(blank=True, null=True, verbose_name='Valor Total')),
                ('cli_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.cliente', verbose_name='Cliente')),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.comanda', verbose_name='Comanda')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.empregado', verbose_name='Empregado')),
                ('fpa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.formapagamento', verbose_name='Forma de Pagamento')),
                ('mesa_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.mesa', verbose_name='Mesa')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('ite_id', models.AutoField(primary_key=True, serialize=False)),
                ('ite_qtde', models.IntegerField(verbose_name='Quantidade de Itens')),
                ('ite_valor', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor das unidades')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.cardapio', verbose_name='Cardapio')),
                ('ped_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do Menu',
                'verbose_name_plural': 'Itens do Menu',
                'db_table': 'item_menu',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('est_id', models.AutoField(primary_key=True, serialize=False)),
                ('est_qtde', models.IntegerField(verbose_name='Quantidade')),
                ('est_validade', models.DateField(verbose_name='Validade')),
                ('est_dataAtual', models.DateField(auto_now_add=True, verbose_name='Data Atual')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.cardapio', verbose_name='Cardapio')),
                ('pro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'db_table': 'estoque',
            },
        ),
        migrations.AddField(
            model_name='empregado',
            name='usu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.usuario', verbose_name='Usuario'),
        ),
    ]
