# Generated by Django 5.1.4 on 2025-01-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecomanda',
            name='ccl_data_abertura',
            field=models.DateTimeField(verbose_name='Data e Hora da Associação'),
        ),
    ]
