# Generated by Django 5.1.4 on 2025-01-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_alter_clientecomanda_ccl_data_abertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientecomanda',
            name='ccl_data_abertura',
            field=models.DateTimeField(verbose_name='Data e Hora da Abertura'),
        ),
        migrations.AlterField(
            model_name='clientecomanda',
            name='ccl_data_fechamento',
            field=models.DateTimeField(null=True, verbose_name='Data e Hora do Fechamento'),
        ),
    ]
