# Generated by Django 5.1.4 on 2025-04-02 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_alter_usuario_options_usuario_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('ing_id', models.AutoField(primary_key=True, serialize=False)),
                ('ing_nome', models.CharField(max_length=28, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'db_table': 'ingrediente',
            },
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='pro_id',
        ),
        migrations.AddField(
            model_name='estoque',
            name='ing_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurante.ingrediente', verbose_name='Ingrediente'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
