# Generated by Django 5.1.4 on 2025-01-20 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_alter_clientecomanda_ccl_data_abertura_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionariocliente',
            name='cli_id',
        ),
        migrations.RemoveField(
            model_name='funcionariocliente',
            name='fun_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='fpa_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='ped_data',
        ),
        migrations.AddField(
            model_name='pedido',
            name='com_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='restaurante.comanda', verbose_name='Comanda'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ped_abertura',
            field=models.DateTimeField(null=True, verbose_name='Abertura'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='ped_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fechamento'),
        ),
        migrations.DeleteModel(
            name='ClienteComanda',
        ),
        migrations.DeleteModel(
            name='FuncionarioCliente',
        ),
    ]
