# Generated by Django 5.1.4 on 2025-01-20 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_remove_funcionariocliente_cli_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fpa_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='restaurante.formapagamento', verbose_name='FormaPagamento'),
        ),
    ]
