# Generated by Django 5.1.4 on 2025-04-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_ingrediente_remove_estoque_pro_id_estoque_ing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ped_dataFechamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fechamento'),
        ),
    ]
