from .auntenticacao import AutenticacaoServices
from .cardapio import CardapioService
from .categoria import CategoriaServices
from .cliente import ClienteService
from .comanda import ComandaServices
from .empregado import EmpregadoService
from .formapagamento import FormaPagamentoServices
from .mesa import MesaServices
from .ingredientes import IngredienteServices
from .pedido import PedidoServices
from .itempedido import ItemPedidoServices
from .estoque import EstoqueServices 